tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/services"
brew "bash-completion"
brew "emacs", restart_service: true
brew "cask"
brew "git"
brew "kubernetes-cli"
brew "mas"
brew "stern"
brew "vcprompt"
cask "diffmerge"
mas "com.microsoft.to-do-mac", id: 1274495053
brew "direnv"
